---
language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
install:
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - flake8 --exit-zero
  - mypy .
  - yamllint .
  - pytest --cov=koles tests/ --cov-branch
after_success: coveralls
