---
language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
install:
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - make flake8
  - make mypy
  - make yamllint
  - make unittests
after_success: coveralls
